### PR TITLE
Use swagger-client@3.8.x module

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
This node outputs an error when executing flow on Node-RED flow editor because the source code is not compatible with the latest swagger-client module. Therefore, I updated the source code for the swagger-client @3.8.x module.

### CODE REVIEW

**Review by codymwalker — APPROVED** [review]

**Comment by kazuhitoyokoi** [comment]
@codymwalker Thank you! I appreciate if you publish the Node-RED node on [npmjs](https://www.npmjs.com/package/node-red-node-swaggerclient). I'd like to use this in my project because it has great functions!

**Comment by kazuhitoyokoi** [comment]
@codymwalker Could you publish this module on npmjs? If there's a problem with it, please let me know.

**Comment by codymwalker** [comment]
@kazuhitoyokoi Sure thing, will do that today.

**Comment by kazuhitoyokoi** [comment]
@codymwalker Thank you for your publishing the node module on npmjs! I will use it on my Node-RED environment. 👍

**Pull request merged**
